# Generated by Django 6.0.4 on 2026-04-18 10:18

import django.db.models.deletion
import nyx.framework.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('cnpj_base', models.CharField(blank=True, max_length=20, verbose_name='Cnpj Base')),
                ('razao_social', models.CharField(blank=True, max_length=150, verbose_name='Razão Social')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('nome_fantasia', models.CharField(blank=True, max_length=150, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(blank=True, max_length=20, verbose_name='Cnpj')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=25, verbose_name='Inscrição Estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=25, verbose_name='Inscrição Municipal')),
                ('cnae', models.CharField(blank=True, max_length=20, verbose_name='Cnae')),
                ('atividade', models.CharField(blank=True, max_length=255, verbose_name='Atividade')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=60, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=5, verbose_name='Uf')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='Cep')),
                ('fone', models.CharField(blank=True, max_length=20, verbose_name='Fone')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='Fax')),
                ('fuso_horario', models.CharField(blank=True, choices=nyx.framework.utils.get_timezone_choices, max_length=50, verbose_name='Fuso Horário')),
                ('logo', models.ImageField(blank=True, upload_to='core/logos/', verbose_name='Logo')),
                ('footer', models.TextField(blank=True, verbose_name='Rodapé')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filiais', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
                'ordering': ['empresa', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_password_change', models.BooleanField(default=True, verbose_name='Forçar troca de senha')),
                ('config', models.JSONField(blank=True, default=dict, null=True, verbose_name='Configurações')),
                ('filiais', models.ManyToManyField(blank=True, to='core.filial', verbose_name='Filiais')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
