# Generated by Django 6.0.4 on 2026-04-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_length', models.PositiveSmallIntegerField(default=8, verbose_name='Mínimo de caracteres')),
                ('require_alpha', models.BooleanField(default=False, verbose_name='Exigir letra')),
                ('require_uppercase', models.BooleanField(default=False, verbose_name='Exigir maiúscula')),
                ('require_digits', models.BooleanField(default=False, verbose_name='Exigir número')),
                ('require_symbols', models.BooleanField(default=False, verbose_name='Exigir símbolo')),
                ('reuse_limit', models.PositiveSmallIntegerField(default=0, help_text='Quantidade de senhas anteriores que não podem ser reutilizadas. Zero desabilita.', verbose_name='Limite de reutilização')),
            ],
            options={
                'verbose_name': 'Política de senhas',
                'verbose_name_plural': 'Política de senhas',
            },
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj_base',
            field=models.CharField(blank=True, help_text='8 primeiros dígitos do CNPJ, sem filial e dígitos verificadores', max_length=20, verbose_name='Cnpj Base'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='cnae',
            field=models.CharField(blank=True, help_text='Classificação Nacional de Atividades Econômicas', max_length=20, verbose_name='Cnae'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='footer',
            field=models.TextField(blank=True, help_text='Usado na geração de relatórios', verbose_name='Rodapé'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='logo',
            field=models.ImageField(blank=True, help_text='Usado na geração de relatórios', upload_to='core/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='uf',
            field=models.CharField(blank=True, max_length=5, verbose_name='UF'),
        ),
    ]
