# Generated by Django 6.0.4 on 2026-04-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_passwordpolicy_alter_empresa_cnpj_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='doc_level',
            field=models.CharField(choices=[('user', 'Usuário'), ('staff', 'Staff')], default='user', max_length=10, verbose_name='Nível de documentação'),
        ),
    ]
